//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:03:53
//
//      Input file      : 
//      Component name  : address_generator
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module Address_Generator(rst_i, CLK25, enable, vsync, address);
   input         rst_i;
   input         CLK25;
   input         enable;
   input         vsync;
   output [16:0] address;
   
   
   reg [16:0]    val;
   
   assign address = val;
   
   
   always @(posedge CLK25)
      
      begin
         
         if (rst_i == 1'b1)
            val <= 17'b0;
         else
         begin
            if (enable == 1'b1)
            begin
               if (val < 320 * 240)
                  val <= val +17'd1;
            end
            if (vsync == 1'b0)
               val <= 17'b0;
         end
      end
   
endmodule
