//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:05:00
//
//      Input file      : 
//      Component name  : counter2
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module counter2(clk, reset, en, count);
   parameter                COUNT_WIDTH = 4;
   input                    clk;
   input                    reset;
   input                    en;
   output [COUNT_WIDTH-1:0] count;
  
   
   reg [1:0]                num;
   
   always @(posedge	clk or posedge reset )
   begin
     
      if (reset == 1'b1)
         num <= 4'd0;
      else if (en == 1'b1)
         num <= num + 1'd1;
     	
   end
   assign count = num;
endmodule
