//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:05:09
//
//      Input file      : 
//      Component name  : debounce
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module debounce(clk, i, o);
   input     clk;
   input     i;
   output    o;
   reg       o;
   
   
   reg [23:0] c;
   
   
   always @(posedge clk)
      
      begin
         if (i == 1'b1)
         begin
            if (c == 24'hFFFFFF)
               o <= 1'b1;
            else
               o <= 1'b0;
            c <= c + 1'd1;
         end
         else
         begin
            c <= 24'b0;
            o <= 1'b0;
         end
      end
   
endmodule
