//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:06:17
//
//      Input file      : 
//      Component name  : feature_calc
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module feature_calc(w0, w1, w2, r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, result_feature);
   input [14:0]    w0;
   input [14:0]    w1;
   input [14:0]    w2;
   input [19:0]    r0;
   input [19:0]    r1;
   input [19:0]    r2;
   input [19:0]    r3;
   input [19:0]    r4;
   input [19:0]    r5;
   input [19:0]    r6;
   input [19:0]    r7;
   input [19:0]    r8;
   input [19:0]    r9;
   input [19:0]    r10;
   input [19:0]    r11;
   output [38:0]   result_feature;
   
   
   wire [36:0]     result_rect0;
   wire [36:0]     result_rect1;
   wire [36:0]     result_rect2;
   wire [(36+1):0] result_rect2_extend;
   wire [(36+1):0] result_temp;
   
   wire            c_out0;
   wire            c_out1;
   
   
   rect_calc rect0(.weight(w0), .a(r0), .b(r1), .c(r2), .d(r3), .result(result_rect0));
   
   
   rect_calc rect1(.weight(w1), .a(r4), .b(r5), .c(r6), .d(r7), .result(result_rect1));
   
   
   rect_calc rect2(.weight(w2), .a(r8), .b(r9), .c(r10), .d(r11), .result(result_rect2));
   
   assign result_temp = {{result_rect0[36], result_rect0}+ {result_rect1[36], result_rect1}};
   
   assign result_rect2_extend[37] = result_rect2[36];
   assign result_rect2_extend[36:0] = result_rect2;
   
   assign result_feature = {{result_rect2_extend[37], result_rect2_extend} +{result_temp[37], result_temp}};
   
endmodule
