//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:07:50
//
//      Input file      : 
//      Component name  : ii_address_mux
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module ii_address_mux(sel, a, b, c, d, q);
   input [1:0]   sel;
   input [14:0]  a;
   input [14:0]  b;
   input [14:0]  c;
   input [14:0]  d;
   output [14:0] q;
   reg [14:0]    q;
   
   
   
   always @(a or b or c or d or sel)
   begin: mux0
      case (sel)
         2'b00 :
            q <= a;
         2'b01 :
            q <= b;
         2'b10 :
            q <= c;
         2'b11 :
            q <= d;
         default :
            q <= {15{1'b0}};
      endcase
   end
   
endmodule

