//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:07:22
//
//      Input file      : 
//      Component name  : ii_address_calc
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module ii_address_calc(x_pos_point, y_pos_point, width_ii, p_offset, ii_address);
   input [4:0]   x_pos_point;
   input [4:0]   y_pos_point;
   input [5:0]   width_ii;
   input [12:0]  p_offset;
   output [12:0] ii_address;
   
   
   wire [10:0]   result_mult0;
   wire [12:0]   reuslt_add0;
   
   assign result_mult0 = (y_pos_point * width_ii);
   
   assign reuslt_add0 = (x_pos_point + p_offset);
   
   assign ii_address = (reuslt_add0 + result_mult0);
   
endmodule
