//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:08:47
//
//      Input file      : 
//      Component name  : iix2_address_decoder
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module iix2_address_decoder(iix2_reg_index, width_ii, p_offset, iix2_address,clk);
   input		 clk;
   input [1:0]   iix2_reg_index;
   input [5:0]   width_ii;
   input [12:0]  p_offset;
   output [12:0] iix2_address;
   reg [12:0]    iix2_address;
   
   
   wire [10:0]   result_mult0;
   
   wire [12:0]   iix2_address0;
   wire [12:0]   iix2_address1;
   wire [12:0]   iix2_address2;
   wire [12:0]   iix2_address3;
   
   assign result_mult0 = (5'd23 * width_ii);
   
   assign iix2_address0 = p_offset;
   
   assign iix2_address1 = (p_offset + 5'd23);
   
   assign iix2_address2 = (p_offset + result_mult0);
   
   assign iix2_address3 = (iix2_address2 + 5'd23);
   
   
   always @(posedge clk)
   begin
      case (iix2_reg_index)
         2'b00 :
            iix2_address <= iix2_address0;
         2'b01 :
            iix2_address <= iix2_address1;
         2'b10 :
            iix2_address <= iix2_address2;
         2'b11 :
            iix2_address <= iix2_address3;
         default :
            iix2_address <= iix2_address0;
      endcase
   end
   
endmodule
