//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:09:44
//
//      Input file      : 
//      Component name  : left_right_tree_mux
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module left_right_tree_mux(sel, left_val, right_val, q);
   input         sel;
   input [13:0]  left_val;
   input [13:0]  right_val;
   output [13:0] q;
   reg [13:0]    q;
   
   
   
   always @(left_val or right_val or sel)
   begin: mux0
      if (sel == 1'b1)
         q <= right_val;
      else
         q <= left_val;
   end
   
endmodule
