//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:09:54
//
//      Input file      : 
//      Component name  : mux_2_1
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module mux_2_1(sel, a, b, q);
   parameter               DATA_WIDTH = 4;
   input                   sel;
   input [DATA_WIDTH-1:0]  a;
   input [DATA_WIDTH-1:0]  b;
   output [DATA_WIDTH-1:0] q;

   
   
   assign q = (sel==1'b1)? b:a;
   
endmodule

