//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:10:02
//
//      Input file      : 
//      Component name  : mux_std_logic
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module mux_std_logic(sel, a, b, q);
   input   sel;
   input   a;
   input   b;
   output  q;
   
   assign q = (sel==1'b1)? b:a;
   
endmodule

