//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:10:29
//
//      Input file      : 
//      Component name  : ov7670_controller
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module ov7670_controller(clk, resend, config_finished, sioc, siod, pwdn, xclk);
   input           clk;
   input           resend;
   output          config_finished;
   output          sioc;
   inout           siod;
   output          pwdn;
   output          xclk;
   
   
   reg             sys_clk;
   wire [15:0]     command;
   wire            finished;
   wire            taken;
   wire            send;
   parameter [7:0] camera_address = 8'h42;
   
   assign config_finished = finished;
   assign send = (~finished);
   
   
   i2c_sender Inst_i2c_sender(
   .clk(clk), 
   .taken(taken), 
   .siod(siod), 
   .sioc(sioc), 
   .send(send), 
   .id(camera_address), 
   .reg_xhdl0(command[15:8]), 
   .value(command[7:0])
   );
   
   assign pwdn = 1'b0;
   assign xclk = sys_clk;
   
   
   ov7670_registers Inst_ov7670_registers(
   .clk(clk), 
   .advance(taken), 
   .command(command), 
   .finished(finished), 
   .resend(resend)
   );
   
   
   always @(posedge clk)
      
         sys_clk <= (~sys_clk);
   
endmodule
