//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:10:57
//
//      Input file      : 
//      Component name  : pixel_offset
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module pixel_offset(mem_state, x_pos_subwin, y_pos_subwin, width_ii, p_offset);
   input         mem_state;
   input [5:0]   x_pos_subwin;
   input [5:0]   y_pos_subwin;
   input [5:0]   width_ii;
   output [12:0] p_offset;
   
   
   wire [12:0]   p_offset_s;
   wire [11:0]   result_mult0;
   
   assign result_mult0 = (y_pos_subwin * width_ii);
   
   assign p_offset_s[12] = (~mem_state);
   assign p_offset_s[11:0] = (result_mult0 + x_pos_subwin);
   assign p_offset = p_offset_s;
   
endmodule
