//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:21:56
//
//      Input file      : 
//      Component name  : rect_mux
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module rect_mux(
   sel,
   a,
   b,
   c,
   q
);
   input [1:0]  sel;		// 2bit unsigned select
   input [4:0]  a;		// 5bit unsigned
   input [4:0]  b;		// 5bit unsigned
   input [4:0]  c;		// 5bit unsigned
   output [4:0] q;		// 5bit unsigned
   reg [4:0]    q;
   
   
   
   always @(a or b or c or sel)
   begin: mux0
      case (sel)
         2'b00 :
            q <= a;
         2'b01 :
            q <= b;
         2'b10 :
            q <= c;
         default :
            q <= {5{1'b0}};
      endcase
   end
   
endmodule

