//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:22:12
//
//      Input file      : 
//      Component name  : register_file2
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module register_file2(
   clk,
   write_en,
   write_reg_addr,
   write_data,
   q0,
   q1,
   q2,
   q3
);
   parameter                 ADDR_WIDTH = 4;
   parameter                 DATA_WIDTH = 18;
   input                     clk;
   input                     write_en;
   input [(ADDR_WIDTH-1):0]  write_reg_addr;
   input [(DATA_WIDTH-1):0]  write_data;
   output [(DATA_WIDTH-1):0] q0;
   output [(DATA_WIDTH-1):0] q1;
   output [(DATA_WIDTH-1):0] q2;
   output [(DATA_WIDTH-1):0] q3;
   
   
   reg [(DATA_WIDTH-1):0]    reg_xhdl0[0:(2**ADDR_WIDTH-1)];
   
   
   always @(posedge clk)
   begin: regFile
       begin
         if (write_en == 1'b1)
            reg_xhdl0[write_reg_addr] <= write_data;
      end 
   end
   assign q0 = reg_xhdl0[0];
   assign q1 = reg_xhdl0[1];
   assign q2 = reg_xhdl0[2];
   assign q3 = reg_xhdl0[3];
   
endmodule
