//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:22:19
//
//      Input file      : 
//      Component name  : rgb
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module RGB(
   Din,
   Nblank,
   R,
   G,
   B
);
   input [11:0] Din;		// niveau de gris du pixels sur 8 bits
   input        Nblank;		// signal indique les zone d'affichage, hors la zone d'affichage
   // les trois couleurs prendre 0
   output [7:0] R;		// les trois couleurs sur 10 bits
   output [7:0] G;
   output [7:0] B;
   
   
   assign R = (Nblank == 1'b1) ? {Din[11:8], Din[11:8]} :    8'b00000000;
            
   assign G = (Nblank == 1'b1) ? {Din[7:4], Din[7:4]} :    8'b00000000;
            
   assign B = (Nblank == 1'b1) ? {Din[3:0], Din[3:0]} :    8'b00000000;
    
   
endmodule
