//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:22:57
//
//      Input file      : 
//      Component name  : vga
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------

// ok, let's brush up our French here; :-)

module VGA(
  	input  	CLK25,
 	output  Hsync,
 	output  Vsync,
 	output  Nblank,
  	output 	activeArea,
	output  Nsync,
	output  VGA_DE
);
  // Horloge d'entre de 75.25 MHz              
  // les deux signaux de synchronisation pour l'ecran VGA
  
  
  // signal de commande du convertisseur N/A ADV7123
  
  // signaux de synchronisation et commande de l'ecran TFT
   
   reg        activeArea_r;
   reg [9:0]  Hcnt;		// pour le comptage des colonnes
   reg [9:0]  Vcnt;		// pour le comptage des lignes
   wire       video;
   parameter  HM = 799;		//la taille maximale considere 800 (horizontal)
   parameter  HD = 640;		//la taille de l'ecran (horizontal)
   parameter  HF = 16;		//front porch
   parameter  HB = 48;		//back porch
   parameter  HR = 96;		//sync time
   parameter  VM = 524;		//la taille maximale considere 525 (vertical)  
   parameter  VD = 480;		//la taille de l'ecran (vertical)
   parameter  VF = 10;		//front porch
   parameter  VB = 33;		//back porch
   parameter  VR = 2;		//retrace
   

//---------------------------------//
// 水平扫描参数的设定1980*1080  60HZ
//--------------------------------//
parameter H_Total		=	2200; //2200
parameter H_Sync		=	44; //44
parameter H_Back		=	148;//148
parameter H_Active	=	1920;   //1920
parameter H_Front		=	88; //88
parameter H_Start		=	192; //192
parameter H_End		=	2172;  //2172
//-------------------------------//
// 垂直扫描参数的设定1920*1080	60HZ  	
//-------------------------------//
parameter V_Total		=	1125;  //1125
parameter V_Sync		=	5;   //5
parameter V_Back		=	37; //37
parameter V_Active	=	1080;  //1080
parameter V_Front		=	3; //3
parameter V_Start		=	42; //42
parameter V_End		=	1122;  //1122


reg[11:0]	x_cnt = 12'd1;


always @(posedge CLK25)	begin	//水平计数
 if(x_cnt==H_Total)
	x_cnt	<=	12'd1;
	else
	x_cnt	<=	x_cnt	+	1;
end

reg	hsync_r = 1'b1;
reg	hs_de	= 1'b0;
always @(posedge CLK25)
begin
 if(x_cnt==1)
	hsync_r	<=	1'b0;
	else if(x_cnt==H_Sync)
	hsync_r	<=	1'b1;

	else if(x_cnt==H_Start)
	hs_de	<=	1'b1;
	else if(x_cnt==H_End)
	hs_de	<=	1'b0;
end

reg[11:0]	y_cnt = 12'd1;		//垂直计数
always @(posedge CLK25)
begin
	if(y_cnt==V_Total)
	y_cnt	<=	12'd1;
	else if(x_cnt==H_Total)
	y_cnt	<=	y_cnt	+	1;
end

reg	vsync_r = 1'b1;
reg	vs_de   = 1'b0;
always @(posedge CLK25)
begin
	 if(y_cnt==1)
	vsync_r	<=	1'b0;
	else if(y_cnt==V_Sync)
	vsync_r	<=	1'b1;
	else if(y_cnt==V_Start)
	vs_de	<=	1'b1;
	else if(y_cnt==V_End)
	vs_de	<=	1'b0;
end
 
 assign	   Hsync = hsync_r;
 assign	   Vsync = vsync_r ;
  assign Nblank = ((x_cnt < H_Active) & (y_cnt < V_Active)) ? 1'b1 : 	1'b0;	// c'est pour utiliser la resolution complete 640 x 480  
   assign VGA_DE =  hs_de	&	vs_de;             

	assign activeArea = (hs_de & vs_de)? 1'b1:1'b0;




   
   
   // initialisation d'un compteur de 0 a 799 (800 pixel par ligne):
   // a chaque front d'horloge en incremente le compteur de colonnes
   // c-a-d du 0 a 799.
   
//   always @(posedge CLK25)
//       begin
//         if (x_cnt == H_Total) begin		// 799
//          
//            if (y_cnt == V_Total) begin		// 524
//              
//               activeArea <= 1'b1;
//            end else begin
//               if (y_cnt < 1080 - 1)
//                  activeArea <= 1'b1;
//              
//            end
//         end else begin
//            if (x_cnt == 1920 - 1)
//               activeArea <= 1'b0;
//           
//         end
//      end 
   
   // generation du signal de synchronisation horizontale Hsync:
   
   //always @(posedge CLK25)
//       begin
//         if (Hcnt >= (HD + HF) & Hcnt <= (HD + HF + HR - 1))		// Hcnt >= 656 and Hcnt <= 751
//            Hsync <= 1'b0;
//         else
//            Hsync <= 1'b1;
//      end 
//   
//   // generation du signal de synchronisation verticale Vsync:
//   
//   always @(posedge CLK25)
//       begin
//         if (Vcnt >= (VD + VF) & Vcnt <= (VD + VF + VR - 1))		//-Vcnt >= 490 and vcnt<= 491
//            Vsync <= 1'b0;
//         else
//            Vsync <= 1'b1;
//      end 
//   
//   // Nblank et Nsync pour commander le covertisseur ADV7123:
   assign Nsync = 1'b1;
//   assign video = ((Hcnt < HD) & (Vcnt < VD)) ? 1'b1 : 	1'b0;	// c'est pour utiliser la resolution complete 640 x 480  
//                 
//   assign Nblank = video;
   
endmodule

