//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? ?? 29 2018 17:23:03
//
//      Input file      : 
//      Component name  : weak_thresh_compare
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module weak_thresh_compare(
   result_feature,
   var_norm_weak_thresh,
   q
);
   input [41:0] result_feature;		// 42 bit signed
   input [37:0] var_norm_weak_thresh;		// 48 bit signed
   output       q;		// assert '1' for strong_accumulator_result > strong_thresh
   
   
   wire [41:0]  var_norm_weak_thresh_extend;		// 42 bit signed
   
   //-- sign extend var_norm_weak_thresh ----
   assign var_norm_weak_thresh_extend[37:0] = var_norm_weak_thresh;
   assign var_norm_weak_thresh_extend[41:38] = {42{var_norm_weak_thresh[37]}};
   
   //-- compare result_feature >= var_norm_weak_thresh_extend ----
   
   lpm_compare_sign42bit_a_ge_b compare0(
      .dataa(result_feature),
      .datab(var_norm_weak_thresh_extend),
      .aeb(),
      .ageb(q)
   );
   
endmodule
